### ISSUE TITLE
issue about training

### ISSUE THREAD

**Issue by zsj8991** [Megvii-Nanjing/CR-DA-Det#18]

**Comment by zsj8991** [comment]
cityscape_2007_train_s
Loaded dataset `cityscape_2007_train_s` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "da_train_net.py", line 383, in <module>
    s_imdb, s_roidb, s_ratio_list, s_ratio_index = combined_roidb(args.s_imdb_name)
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/roi_da_data_layer/roidb.py", line 131, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split("+")]
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/roi_da_data_layer/roidb.py", line 131, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split("+")]
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/roi_da_data_layer/roidb.py", line 127, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/roi_da_data_layer/roidb.py", line 107, in get_training_roidb
    imdb.append_flipped_images()  #  data augment
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/datasets/imdb.py", line 121, in append_flipped_images
    boxes = self.roidb[i]["boxes"].copy()
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/datasets/imdb.py", line 75, in roidb
    self._roidb = self.roidb_handler()
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/datasets/cityscape.py", line 148, in gt_roidb
    cache_file = os.path.join(self.cache_path, self.name + "_gt_roidb.pkl")
  File "/2T/zsj/CR-DA-DET-master/DA_Faster_ICR_CCR/lib/datasets/imdb.py", line 84, in cache_path
    os.makedirs(cache_path)
  File "/nvidia/yes/envs/crda_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nvidia/yes/envs/crda_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nvidia/yes/envs/crda_env/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nvidia/yes/envs/crda_env/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
